## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0
  - 1.1
  - nightly
matrix:
  allow_failures:
    julia: nightly
notifications:
  email: false
git:
  depth: 99999999

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Expectations"); Pkg.test("Expectations"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; cd(Pkg.dir("Expectations")); pkg"add Coverage"; using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("Expectations")); pkg"add Coverage"; using Coverage; Codecov.submit(Codecov.process_folder())'
  # build documentation
  - julia -e 'using Pkg; pkg"add Documenter"; cd(Pkg.dir("Expectations")); include(joinpath("docs", "make.jl"))'
